#include "ip.h"
#include "icmp.h"
#include "packet.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

#include "log.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	fprintf(stderr, "TODO: longest prefix match for the packet.\n");
	rt_entry_t *p = NULL;
	rt_entry_t *match_entry = NULL;
	u32 max_mask = 0;
	list_for_each_entry(p, &rtable, list){
		if((dst & p->mask) == (p->dest & p->mask)){
			if(p->mask > max_mask){
				max_mask = p->mask;
				match_entry = p;
			}
		}
	}
	return match_entry;
}


// forward the IP packet from the interface specified by longest_prefix_match, 
// when forwarding the packet, you should check the TTL, update the checksum,
// determine the next hop to forward the packet, then send the packet by 
// iface_send_packet_by_arp
// void ip_forward_packet(u32 ip_dst, char *packet, int len)
// {
// 	fprintf(stderr, "TODO: forward ip packet.\n");
 
// }

// send IP packet

// Different from ip_forward_packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	fprintf(stderr, "TODO: send ip packet.\n");
	rt_entry_t *p = NULL;
	struct iphdr *ip = packet_to_ip_hdr(packet);
	struct ether_header *eh = (struct ether_header *)(packet);

	p = longest_prefix_match(ntohl(ip->daddr));
	if(!p){
		// icmp_send_packet(packet, len, ICMP_DEST_UNREACH, ICMP_NET_UNREACH);
		// log(ERROR, "couldn't find forward rule for IP(dest:"IP_FMT")", HOST_IP_FMT_STR(dst));
		free(packet);
		return;
	}
	eh->ether_type = ntohs(ETH_P_IP);
	memcpy(eh->ether_shost, p->iface->mac, ETH_ALEN);


	//determin next hop
	u32 next_hop = p->gw;
	if(!next_hop)
		next_hop = ntohl(ip->daddr);

	printf("%s"IP_FMT"\n", "ip_send: Next Hop is... ", HOST_IP_FMT_STR(next_hop));

	iface_send_packet_by_arp(p->iface, next_hop, packet, len);

}
